spring:
  datasource:
    url: jdbc:mysql://it-db-instance.cdpvxppiskfr.ap-northeast-1.rds.amazonaws.com:3306/sample
    username: root
    password: mysql

flyway:
  url: jdbc:mysql://it-db-instance.cdpvxppiskfr.ap-northeast-1.rds.amazonaws.com:3306/sample
  user: root
  password: mysql