db:
    image: mysql:5.6
    container_name: database
    ports:
     - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=sample
